### ISSUE TITLE
App won't open (TS-419+, Firmware version 4.3.3.2211)

### ISSUE THREAD

**Issue by jessethibo** [tailscale/tailscale-qpkg#73]
Downloaded and manually installed Tailscale_v1.34.1_arm-x19.qpkg successfully through the QNAP APP Center. App won't open when clicking on the open button.

**Comment by bradfitz** [comment]
Did you previously have Tailscale installed on there?

Anything in logs?

**Comment by jessethibo** [comment]
This is my first time attempting to install Tailscale on this NAS

**Comment by jessethibo** [comment]
![image](https://user-images.githubusercontent.com/123222415/213841762-a7a17b22-2c0c-4450-af8a-1413ea06aab6.png)

I installed it once and saw that it wasn't working so then proceeded to remove it and install it again to see if it was just a bad install but same issue occurs.

**Comment by bradfitz** [comment]
Is the tailscaled process running? Any logs from it?

**Comment by jessethibo** [comment]
How do I check?

**Comment by DentonGentry** [comment]
Since you're running the 1.34.1 build, the instructions are at: https://github.com/tailscale/tailscale-qpkg/tree/update
They involve using SSH, instead of clicking on the icon.

The instructions you're trying to follow are for the version of the app which has been sent to QNAP for inclusion in the App Center. Unfortunately we recently determined that x19 products don't work with that build, so the earlier SSH instructions will need to be followed.

**Comment by jessethibo** [comment]
I tried authorizing my client using: **_./tailscale -socket var/run/tailscale/tailscaled.sock up_** and then it gives me a message saying **_Failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)_** . I then tried the command _**sudo systemctl start tailscaled**_ and it tells me command not found.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale-qpkg/releases/tag/qnap-1.36.0 includes an x19 package.

**Comment by KilllerRabbbit** [comment]
> Did you previously have Tailscale installed on there?

Is there any special installation procedure for users of previous builds?
When I installed 1.34.2 package over the previous one I lost whole network connectivity between QNAP and my local network. It was accessible via Tailscale only.

**Comment by jessethibo** [comment]
@DentonGentry It won't install because my NAS doesn't support QTS 5 or newer versions of the firmware yet. My best bet would be to build my own NAS and move away from proprietary stuff like QNAP.

**Comment by DentonGentry** [comment]
>Is there any special installation procedure for users of previous builds?

No, there is not a special install procedure. Earlier in this thread we were trying to determine why the package wasn't starting on the QNAP in question.

**Comment by HansRen1024** [comment]
> I tried authorizing my client using: **_./tailscale -socket var/run/tailscale/tailscaled.sock up_** and then it gives me a message saying **_Failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)_** . I then tried the command _**sudo systemctl start tailscaled**_ and it tells me command not found.

I got the same problem on my QNAP TS-412, the system version is 4.3.3. I tried Tailscale_1.30.0-1_arm-x19.qpkg to Tailscale_1.30.0-1_arm-x19.qpkg. No one works.

**Comment by shingoxray** [comment]
Same problem. TAS-268 with QTS 4.3.3, tailscaled won't run.

**Comment by DentonGentry** [comment]
The recent QNAP builds require QTS5. The package is supposed to decline to install on QTS4.

The last version which works on QTS4 is https://github.com/tailscale/tailscale-qpkg/releases/tag/v1.34.1, which can join a tailnet and interoperate with nodes running other Tailscale releases.

**Comment by shingoxray** [comment]
When I try to bring up tailscaled, there is a error:
```shell
panic: bufio: reader returned negative count from Read

goroutine 1 [running]:
bufio.(*Reader).Read(0x2865080, {0x28246c8, 0x4, 0x4})
	/media/ware4/Entware.2023.02/staging_dir/host/go/src/bufio/bufio.go:239 +0x3c0
gvisor.dev/gvisor/pkg/rand.(*bufferedReader).Read(0x1042360, {0x28246c8, 0x4, 0x4})
	/media/ware4/Entware.2023.02/tmp/go-build/pkg/mod/gvisor.dev/gvisor@v0.0.0-20221203005347-703fd9b7fbc0/pkg/rand/rand_linux.go:58 +0x4c
io.ReadAtLeast({0xb2435c, 0x1042360}, {0x28246c8, 0x4, 0x4}, 0x4)
	/media/ware4/Entware.2023.02/staging_dir/host/go/src/io/io.go:332 +0x90
io.ReadFull(...)
	/media/ware4/Entware.2023.02/staging_dir/host/go/src/io/io.go:351
gvisor.dev/gvisor/pkg/rand.Read({0x28246c8, 0x4, 0x4})
	/media/ware4/Entware.2023.02/tmp/go-build/pkg/mod/gvisor.dev/gvisor@v0.0.0-20221203005347-703fd9b7fbc0/pkg/rand/rand_linux.go:68 +0x48
gvisor.dev/gvisor/pkg/tcpip/network/hash.RandN32(0x1)
	/media/ware4/Entware.2023.02/tmp/go-build/pkg/mod/gvisor.dev/gvisor@v0.0.0-20221203005347-703fd9b7fbc0/pkg/tcpip/network/hash/hash.go:30 +0x4c
gvisor.dev/gvisor/pkg/tcpip/network/hash.init()
	/media/ware4/Entware.2023.02/tmp/go-build/pkg/mod/gvisor.dev/gvisor@v0.0.0-20221203005347-703fd9b7fbc0/pkg/tcpip/network/hash/hash.go:25 +0x1c
```
What should I do?

**Comment by DentonGentry** [comment]
Did you compile this yourself? `/media/ware4/Entware.2023.02` is not a directory we use.

`/media/ware4/Entware.2023.02/staging_dir/host/go/src/bufio/bufio.go`

**Comment by shingoxray** [comment]
Sorry. I installed this one by using Entware(opkg). But the one in this repo (Tailscale_v1.34.1_arm-x41.qpkg) produces the same error:
```shell
[/share/CACHEDEV1_DATA/.qpkg/Tailscale] # ./Tailscale.sh start
[/share/CACHEDEV1_DATA/.qpkg/Tailscale] # ./tailscale status
failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)
[/share/CACHEDEV1_DATA/.qpkg/Tailscale] # ./tailscaled
panic: bufio: reader returned negative count from Read

goroutine 1 [running]:
bufio.(*Reader).Read(0x2903020, {0x2824768, 0x4, 0x4})
	/root/.cache/tailscale-go/src/bufio/bufio.go:239 +0x3c0
gvisor.dev/gvisor/pkg/rand.(*bufferedReader).Read(0xff15c8, {0x2824768, 0x4, 0x4})
	/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220817001344-846276b3dbc5/pkg/rand/rand_linux.go:58 +0x4c
io.ReadAtLeast({0xb181d8, 0xff15c8}, {0x2824768, 0x4, 0x4}, 0x4)
	/root/.cache/tailscale-go/src/io/io.go:332 +0x90
io.ReadFull(...)
	/root/.cache/tailscale-go/src/io/io.go:351
gvisor.dev/gvisor/pkg/rand.Read({0x2824768, 0x4, 0x4})
	/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220817001344-846276b3dbc5/pkg/rand/rand_linux.go:68 +0x48
gvisor.dev/gvisor/pkg/tcpip/network/hash.RandN32(0x1)
	/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220817001344-846276b3dbc5/pkg/tcpip/network/hash/hash.go:30 +0x4c
gvisor.dev/gvisor/pkg/tcpip/network/hash.init()
	/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220817001344-846276b3dbc5/pkg/tcpip/network/hash/hash.go:25 +0x1c
```
